Custom Fields Translation
OnTheGoSystems/multilingual-tools pull request #28
Opened 2023-07-13 17:49 UTC by amElnagdy

Adding new menu item under Multilingual Tools  → Custom Fields Translation.

2023-07-14 17:38 UTC, dgwatkins commented on inc/class-mltools-custom-fields-translation.php
> +			$date_errors = DateTime::getLastErrors();
@amElnagdy Can you wrap the above 2 lines with `if ( $value ) { ... }` because otherwise it throws an error with PH P 8.1

2023-07-14 17:40 UTC, dgwatkins commented on inc/class-mltools-custom-fields-translation.php
> +			$isHashString = strlen( $value ) > 5 && preg_match( '/\d/', $value ) && preg_match( '/[a-zA-Z]/', $value ) && strpos( $value, ' ' ) === false;
`$value` can be `null` and `strlen` throws an error. try with this @amElnagdy 
```suggestion
			$isHashString = $value && strlen( $value ) > 5 && preg_match( '/\d/', $value ) && preg_match( '/[a-zA-Z]/', $value ) && strpos( $value, ' ' ) === false;
```

2023-07-14 17:42 UTC, dgwatkins commented on inc/wpml-compatibility-test-tools.class.php
> +		add_submenu_page( 'mt', __( 'Custom Fields Translation', 'wpml-compatibility-test-tools' ), __( 'Custom Fields Translation', 'wpml-compatibility-test-tools' ), 'manage_options', 'cf-translations',
@amElnagdy The title is a bit confusing. It makes me think its going to help translate but its really helping me with translation preferences.

Maybe 'Custom Field Settings Helper' would be better? or something along those lines ...

2023-07-14 17:44 UTC, dgwatkins commented on menus/settings/custom-fields-translation.php
> +						if ( strlen( $value ) > $maxLength ) {
@amElnagdy This also throws an error when its null:
```suggestion
						if ( $value && strlen( $value ) > $maxLength ) {
```

2023-07-14 17:47 UTC, dgwatkins requested changes
I am currently running PHP 8.1 so I found a few minor issues that we can already fix.

2023-07-14 18:04 UTC, amElnagdy commented
> I am currently running PHP 8.1 so I found a few minor issues that we can already fix.

Thank you, @dgwatkins! I switched to 8.1 after doing the requested changes and ran a few tests and all looks good now. Thank you, again!

2023-10-13 09:54 UTC, dgwatkins approved these changes

2023-10-13 10:33 UTC, merged