XML Generator for Elementor Widgets
OnTheGoSystems/multilingual-tools pull request #29
Opened 2023-09-04 19:44 UTC by diiegopereira

See compsupp-6861

2023-09-05 06:41 UTC, strategio approved these changes
@diiegopereira, looks good to me! It will help a lot +1

I am just leaving some comments about formatting (if you want to upgrade the code):
- Now we just use shorthand arrays (`[]` instead of `array()`)
- We give some spaces inside parenthesis or brackets with variable keys.
- We try to align equal signs.

You can to follow the WP PHP coding standards => https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/

Let me know if you want me to merge right now or not.

2023-09-08 13:14 UTC, diiegopereira commented
Thanks @strategio ! I improved the code formatting. If it's ok, we can merge.

2023-09-08 14:10 UTC, dgwatkins commented on inc/class-mltools-elementor-config-generator.php
> +				$widgets[ $widgetType ]['settings']   = $settings;
@diiegopereira I am not sure how far you want to go with this.

The 3 equal signs above should be aligned according to standards.

2023-09-08 14:10 UTC, dgwatkins commented on inc/class-mltools-elementor-config-generator.php
> +					$settings[ $field_key ]   = $this->get_field_from_widget( $field_key, $field_value, $widgetType );
This one has too many spaces @diiegopereira 
```suggestion
					$settings[ $field_key ] = $this->get_field_from_widget( $field_key, $field_value, $widgetType );
```

2023-09-08 14:11 UTC, dgwatkins commented on inc/class-mltools-elementor-config-generator.php
> +				$widgets                      = array_merge( $widgets, $this->get_widgets_list( $element->elements ) );
@diiegopereira and this one too:
```suggestion
				$widgets = array_merge( $widgets, $this->get_widgets_list( $element->elements ) );
```

2023-09-08 14:12 UTC, dgwatkins commented on inc/class-mltools-elementor-config-generator.php
> +				$settings                      = (array) get_object_vars( $element->settings );
... and this one:
```suggestion
				$widgetType = $element->widgetType;
				$settings   = (array) get_object_vars( $element->settings );
```

2023-09-08 14:14 UTC, dgwatkins requested changes
I'll take over @diiegopereira because Pierre wont be around until next Tuesday.

One of the coding standard says that equal signs need to be aligned. And with the least number of spaces.

I made a few comments but there are more instances of this mistake. 

Since you are bringing the code up to standards, I thought this would be a good update.

2023-09-27 18:18 UTC, diiegopereira commented
@dgwatkins sorry, I tried to format manually + with ChatGPT but it not worked as expected.

Now, Instead of doing manually, I tried to format the code using php-cs-fixer and wp-php-cs-fixer (so it can be done automatically in the future). Could you please check if it worked correctly?

2023-09-28 09:04 UTC, dgwatkins approved these changes
It looks so much better now.

2023-09-28 09:06 UTC, merged